apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2 
kind: Deployment 
metadata: 
  name: devops-deployment 
spec: 
  selector: 
    matchLabels: 
      app: devops 
  replicas: 5 # tells deployment to run 2 pods matching the template 
  template:
    metadata: 
      labels: 
        app: devops 
    spec: 
      containers: 
      - name: devops 
        image: samehzaghbib/devops:#{Build.BuildId}#
        ports: 
        - containerPort: 80 
--- 
# https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service  
kind: Service 
apiVersion: v1 
metadata: 
  name: devops-service 
spec: 
  selector: 
    app: devops 
  ports: 
  - protocol: TCP 
    port: 80 
    targetPort: 80 
  type: LoadBalancer 